name: mvvm_architecture_with_api_and_provider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  http: 
  provider: ^6.1.2
  fluttertoast: ^8.2.4
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
